### ISSUE TITLE
Additional notification types

### ISSUE THREAD

**Issue by wavebeem** [svipas/vscode-notification-tester#1]
I believe it's possible to have notifications with buttons and/or links. It would be nice if this extension could show these notification types as well.

P.S. Thanks for making this extension!!!

**Comment by svipas** [comment]
@wavebeem Update Notification Tester to 1.1.0 version and you will see buttons.

![](https://raw.githubusercontent.com/svipben/vscode-notification-tester/master/images/notification-center.png)

**Comment by wavebeem** [comment]
Thank you! Works great over here
