### ISSUE TITLE
Add test for busy clock notification icon

### ISSUE THREAD

**Issue by tweakimp** [svipas/vscode-notification-tester#2]
See https://github.com/Microsoft/vscode/issues/44604

It would be great to test this with your extension, too :)

**Comment by svipas** [comment]
Thanks for the suggestion. I will try to do it. How to call this command? `Show Progress Badge`?

**Comment by tweakimp** [comment]
Thanks for the quick reply. Yes, `Show Progress Badge` sounds good.

**Comment by svipas** [comment]
@tweakimp I can add progress badge in Source Control see screenshot below. It will never end except you stop it with another command called "Stop Progress Badge".

![image](https://user-images.githubusercontent.com/10441177/38205700-2f238b74-36b0-11e8-9a87-b789f43e8c42.png)

**Comment by tweakimp** [comment]
That should also work, thanks :)

**Comment by svipas** [comment]
@tweakimp Already done and the new version is published. 🎉
