### ISSUE TITLE
Accept notification message

### ISSUE THREAD

**Issue by Akv2021** [svipas/vscode-notification-tester#8]
Hi,
It would increase the usability of this task for many users if we have an option to pass a message to the notification shown.

Example Use case : 
The [Settings Cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler) extension allows us to toggle between two sets of settings. So, in this case I can show a message showing which set of settings was invoked.

There are other extensions like [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command) which can make use of this functionality in a similar fashion.

Lastly, it would help even if some variants of notification types (like Information/Error message) can support the custom message.

**Comment by svipas** [comment]
I believe you misunderstood why this extension exists. It's to test a VS Code notifications to simply look how error/info/warning and progress badge looks like. It's mostly used for VS Code theme development.
